### ISSUE TITLE
Reversed order of weather data

### ISSUE THREAD

**Issue by Degamisu** [Degamisu/Console-Weather-App#7]
Don't know what is going on or how to fix. The weather shows the oldest data in the `open-metro` database. not the latest.

**Comment by ankit-pn** [comment]
hey i would love to work on it. pls assign this to me!

**Comment by Degamisu** [comment]
I appreciate the help!

**Comment by Degamisu** [comment]
> hey i would love to work on it. pls assign this to me!

progress update?

**Comment by ankit-pn** [comment]
Hey, extremely sorry that I was not able to finish this issue till now as I was busy working on something else. I will try to finish this by tomorrow, if that works for you?

**Comment by Degamisu** [comment]
> Hey, extremely sorry that I was not able to finish this issue till now as I was busy working on something else. I will try to finish this by tomorrow, if that works for you?

no issues! your alright. (im _extremely_ flexible. a month would be minuscule for my patience lol.)

**Comment by Degamisu** [comment]
I just updated the `main.py`. The new code is:

```python
    def display_hourly_weather(self, weather_data):
        max_rows, _ = self.screen.getmaxyx()
        rows_to_display = min(max_rows - 18, len(weather_data['hourly']['time']) * 5)

        times = list(reversed(weather_data['hourly']['time']))
        temperatures = list(reversed(weather_data['hourly']['temperature_2m']))
        relative_humidity = list(reversed(weather_data['hourly']['relative_humidity_2m']))
        wind_speeds = list(reversed(weather_data['hourly']['wind_speed_10m']))

        self.center_text("Weather in the Last Hour:", 16)

        for i, time_data in enumerate(zip(times, temperatures, relative_humidity, wind_speeds), start=18):
            if i + 4 > 18 + rows_to_display:
                break

            self.center_text(f"Time: {time_data[0]}", i)
            self.center_text(f"Temperature: {time_data[1]}°C", i + 1)
            self.center_text(f"Relative Humidity: {time_data[2]}%", i + 2)
            self.center_text(f"Wind Speed: {time_data[3]} m/s", i + 3)
            self.center_text("---", i + 4)

        self.screen.refresh()  # Refresh the main screen after making changes
```

This should fix the issue. I will build this soon.
